Meteor.methods({
	uploadLSI:function(lsiObject,userid){
		LSIs.insert(lsiObject);
		Meteor.users.update({
			_id:userid
		},{
			$push:{
				'profile.codeContributions':lsiObject._id
			}
		});
	}
});
