Meteor.methods({
	updateProfile:function(profObj,userID){
		Meteor.users.update({
			_id:userID
		},{
			$set:{
				'profile.lastname':profObj.lastname,
				'profile.firstname':profObj.firstname,
				'profile.email':profObj.emailNew
			}
		},{
			upsert:true
		});
	} 
});
