Meteor.methods({
	updateProfile:function(prof,userID){
		Meteor.users.update({
			_id:userID
		},{
			$set:{
				'profile.lastname':prof.lastname,
				'profile.email':prof.email,
				'profile.firstname':prof.firstname
			}
		},{
			upsert:true
		});
	} 
});
